name: Enforce Branch Naming Convention

on:
  create:
    branches:
      - '**'

jobs:
  check-branch-name:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Enforce branch naming convention
        run: |
          BRANCH_NAME=$(echo ${{ github.ref }} | sed 's|refs/heads/||')
          if [[ ! $BRANCH_NAME =~ ^(feature|hotfix|bugfix)-cwis-[0-9]{4}-[a-z0-9-]{1,20}$ ]]; then
            echo "Branch name '$BRANCH_NAME' does not follow the naming convention."
            exit 1
          fi
