name: Enforce Branch Naming Convention

on:
  push:
    branches:
      - "**"

jobs:
  check-branch-name:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Validate branch name
        env:
          BRANCH_NAME: ${{ github.ref }}
        run: |
          if [[ ! "$BRANCH_NAME" =~ ^(refs/heads/)?(feature|hotfix|bugfix)-cwis-[0-9]{4}-[a-zA-Z0-9-]{1,20}$ ]]; then
            echo "Invalid branch name: $BRANCH_NAME"
            echo "Branch names should follow the pattern: (feature|hotfix|bugfix)-cwis-1234-short-20-char-text"
            exit 1
          fi
